// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_logs.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createActivityLog = `-- name: CreateActivityLog :exec
INSERT INTO activity_logs (id, board_id, card_id, user_id, action, entity_type, entity_title, details, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
`

type CreateActivityLogParams struct {
	ID          uuid.UUID      `json:"id"`
	BoardID     uuid.UUID      `json:"board_id"`
	CardID      uuid.NullUUID  `json:"card_id"`
	UserID      uuid.UUID      `json:"user_id"`
	Action      string         `json:"action"`
	EntityType  string         `json:"entity_type"`
	EntityTitle string         `json:"entity_title"`
	Details     sql.NullString `json:"details"`
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) error {
	_, err := q.db.Exec(ctx, createActivityLog,
		arg.ID,
		arg.BoardID,
		arg.CardID,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityTitle,
		arg.Details,
	)
	return err
}

const listActivityLogsByBoard = `-- name: ListActivityLogsByBoard :many
SELECT a.id, a.board_id, a.card_id, a.user_id, a.action, a.entity_type, a.entity_title, a.details, a.created_at,
       u.name AS user_name, u.avatar_url AS user_avatar_url
FROM activity_logs a
JOIN users u ON u.id = a.user_id
WHERE a.board_id = $1
ORDER BY a.created_at DESC
LIMIT $2 OFFSET $3
`

type ListActivityLogsByBoardParams struct {
	BoardID uuid.UUID `json:"board_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

type ListActivityLogsByBoardRow struct {
	ID            uuid.UUID      `json:"id"`
	BoardID       uuid.UUID      `json:"board_id"`
	CardID        uuid.NullUUID  `json:"card_id"`
	UserID        uuid.UUID      `json:"user_id"`
	Action        string         `json:"action"`
	EntityType    string         `json:"entity_type"`
	EntityTitle   string         `json:"entity_title"`
	Details       sql.NullString `json:"details"`
	CreatedAt     time.Time      `json:"created_at"`
	UserName      string         `json:"user_name"`
	UserAvatarUrl sql.NullString `json:"user_avatar_url"`
}

func (q *Queries) ListActivityLogsByBoard(ctx context.Context, arg ListActivityLogsByBoardParams) ([]ListActivityLogsByBoardRow, error) {
	rows, err := q.db.Query(ctx, listActivityLogsByBoard, arg.BoardID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityLogsByBoardRow{}
	for rows.Next() {
		var i ListActivityLogsByBoardRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.CardID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityTitle,
			&i.Details,
			&i.CreatedAt,
			&i.UserName,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityLogsByCard = `-- name: ListActivityLogsByCard :many
SELECT a.id, a.board_id, a.card_id, a.user_id, a.action, a.entity_type, a.entity_title, a.details, a.created_at,
       u.name AS user_name, u.avatar_url AS user_avatar_url
FROM activity_logs a
JOIN users u ON u.id = a.user_id
WHERE a.card_id = $1
ORDER BY a.created_at DESC
LIMIT $2 OFFSET $3
`

type ListActivityLogsByCardParams struct {
	CardID uuid.NullUUID `json:"card_id"`
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
}

type ListActivityLogsByCardRow struct {
	ID            uuid.UUID      `json:"id"`
	BoardID       uuid.UUID      `json:"board_id"`
	CardID        uuid.NullUUID  `json:"card_id"`
	UserID        uuid.UUID      `json:"user_id"`
	Action        string         `json:"action"`
	EntityType    string         `json:"entity_type"`
	EntityTitle   string         `json:"entity_title"`
	Details       sql.NullString `json:"details"`
	CreatedAt     time.Time      `json:"created_at"`
	UserName      string         `json:"user_name"`
	UserAvatarUrl sql.NullString `json:"user_avatar_url"`
}

func (q *Queries) ListActivityLogsByCard(ctx context.Context, arg ListActivityLogsByCardParams) ([]ListActivityLogsByCardRow, error) {
	rows, err := q.db.Query(ctx, listActivityLogsByCard, arg.CardID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityLogsByCardRow{}
	for rows.Next() {
		var i ListActivityLogsByCardRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.CardID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityTitle,
			&i.Details,
			&i.CreatedAt,
			&i.UserName,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
