// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (id, card_id, user_id, file_name, file_url, file_size, file_type, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
RETURNING id, card_id, user_id, file_name, file_url, file_size, file_type, created_at
`

type CreateAttachmentParams struct {
	ID       uuid.UUID      `json:"id"`
	CardID   uuid.UUID      `json:"card_id"`
	UserID   uuid.UUID      `json:"user_id"`
	FileName string         `json:"file_name"`
	FileUrl  string         `json:"file_url"`
	FileSize sql.NullInt32  `json:"file_size"`
	FileType sql.NullString `json:"file_type"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.ID,
		arg.CardID,
		arg.UserID,
		arg.FileName,
		arg.FileUrl,
		arg.FileSize,
		arg.FileType,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.UserID,
		&i.FileName,
		&i.FileUrl,
		&i.FileSize,
		&i.FileType,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM attachments WHERE id = $1
`

func (q *Queries) DeleteAttachment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttachment, id)
	return err
}

const getAttachmentByID = `-- name: GetAttachmentByID :one
SELECT id, card_id, user_id, file_name, file_url, file_size, file_type, created_at
FROM attachments
WHERE id = $1
`

func (q *Queries) GetAttachmentByID(ctx context.Context, id uuid.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentByID, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.UserID,
		&i.FileName,
		&i.FileUrl,
		&i.FileSize,
		&i.FileType,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentsByCard = `-- name: ListAttachmentsByCard :many
SELECT a.id, a.card_id, a.user_id, a.file_name, a.file_url, a.file_size, a.file_type, a.created_at,
       u.name AS user_name, u.avatar_url AS user_avatar_url
FROM attachments a
JOIN users u ON u.id = a.user_id
WHERE a.card_id = $1
ORDER BY a.created_at DESC
`

type ListAttachmentsByCardRow struct {
	ID            uuid.UUID      `json:"id"`
	CardID        uuid.UUID      `json:"card_id"`
	UserID        uuid.UUID      `json:"user_id"`
	FileName      string         `json:"file_name"`
	FileUrl       string         `json:"file_url"`
	FileSize      sql.NullInt32  `json:"file_size"`
	FileType      sql.NullString `json:"file_type"`
	CreatedAt     time.Time      `json:"created_at"`
	UserName      string         `json:"user_name"`
	UserAvatarUrl sql.NullString `json:"user_avatar_url"`
}

func (q *Queries) ListAttachmentsByCard(ctx context.Context, cardID uuid.UUID) ([]ListAttachmentsByCardRow, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByCard, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttachmentsByCardRow{}
	for rows.Next() {
		var i ListAttachmentsByCardRow
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.UserID,
			&i.FileName,
			&i.FileUrl,
			&i.FileSize,
			&i.FileType,
			&i.CreatedAt,
			&i.UserName,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
