// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCard = `-- name: CreateCard :one
INSERT INTO cards (id, list_id, title, description, position, priority, due_date, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW())
RETURNING id, list_id, title, description, position, priority, due_date, created_at, updated_at
`

type CreateCardParams struct {
	ID          uuid.UUID      `json:"id"`
	ListID      uuid.UUID      `json:"list_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Position    float64        `json:"position"`
	Priority    Priority       `json:"priority"`
	DueDate     sql.NullTime   `json:"due_date"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.ID,
		arg.ListID,
		arg.Title,
		arg.Description,
		arg.Position,
		arg.Priority,
		arg.DueDate,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM cards WHERE id = $1
`

func (q *Queries) DeleteCard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCard, id)
	return err
}

const getCardByID = `-- name: GetCardByID :one
SELECT id, list_id, title, description, position, priority, due_date, created_at, updated_at
FROM cards
WHERE id = $1
`

func (q *Queries) GetCardByID(ctx context.Context, id uuid.UUID) (Card, error) {
	row := q.db.QueryRow(ctx, getCardByID, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMaxPositionForList = `-- name: GetMaxPositionForList :one
SELECT COALESCE(MAX(position), 0)::float8 FROM cards WHERE list_id = $1
`

func (q *Queries) GetMaxPositionForList(ctx context.Context, listID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getMaxPositionForList, listID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const listCardsByList = `-- name: ListCardsByList :many
SELECT id, list_id, title, description, position, priority, due_date, created_at, updated_at
FROM cards
WHERE list_id = $1
ORDER BY position ASC
`

func (q *Queries) ListCardsByList(ctx context.Context, listID uuid.UUID) ([]Card, error) {
	rows, err := q.db.Query(ctx, listCardsByList, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCard = `-- name: UpdateCard :one
UPDATE cards
SET list_id = $2, title = $3, description = $4, position = $5, priority = $6, due_date = $7, updated_at = NOW()
WHERE id = $1
RETURNING id, list_id, title, description, position, priority, due_date, created_at, updated_at
`

type UpdateCardParams struct {
	ID          uuid.UUID      `json:"id"`
	ListID      uuid.UUID      `json:"list_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Position    float64        `json:"position"`
	Priority    Priority       `json:"priority"`
	DueDate     sql.NullTime   `json:"due_date"`
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, updateCard,
		arg.ID,
		arg.ListID,
		arg.Title,
		arg.Description,
		arg.Position,
		arg.Priority,
		arg.DueDate,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
