// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (id, card_id, user_id, content, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id, card_id, user_id, content, created_at, updated_at
`

type CreateCommentParams struct {
	ID      uuid.UUID `json:"id"`
	CardID  uuid.UUID `json:"card_id"`
	UserID  uuid.UUID `json:"user_id"`
	Content string    `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.ID,
		arg.CardID,
		arg.UserID,
		arg.Content,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, card_id, user_id, content, created_at, updated_at
FROM comments
WHERE id = $1
`

func (q *Queries) GetCommentByID(ctx context.Context, id uuid.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCommentsByCard = `-- name: ListCommentsByCard :many
SELECT c.id, c.card_id, c.user_id, c.content, c.created_at, c.updated_at,
       u.name AS user_name, u.avatar_url AS user_avatar_url
FROM comments c
JOIN users u ON u.id = c.user_id
WHERE c.card_id = $1
ORDER BY c.created_at DESC
`

type ListCommentsByCardRow struct {
	ID            uuid.UUID      `json:"id"`
	CardID        uuid.UUID      `json:"card_id"`
	UserID        uuid.UUID      `json:"user_id"`
	Content       string         `json:"content"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	UserName      string         `json:"user_name"`
	UserAvatarUrl sql.NullString `json:"user_avatar_url"`
}

func (q *Queries) ListCommentsByCard(ctx context.Context, cardID uuid.UUID) ([]ListCommentsByCardRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByCard, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsByCardRow{}
	for rows.Next() {
		var i ListCommentsByCardRow
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments
SET content = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, card_id, user_id, content, created_at, updated_at
`

type UpdateCommentParams struct {
	ID      uuid.UUID `json:"id"`
	Content string    `json:"content"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.ID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
