// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lists.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createList = `-- name: CreateList :one
INSERT INTO lists (id, board_id, name, position, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id, board_id, name, position, created_at, updated_at
`

type CreateListParams struct {
	ID       uuid.UUID `json:"id"`
	BoardID  uuid.UUID `json:"board_id"`
	Name     string    `json:"name"`
	Position float64   `json:"position"`
}

func (q *Queries) CreateList(ctx context.Context, arg CreateListParams) (List, error) {
	row := q.db.QueryRow(ctx, createList,
		arg.ID,
		arg.BoardID,
		arg.Name,
		arg.Position,
	)
	var i List
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteList = `-- name: DeleteList :exec
DELETE FROM lists WHERE id = $1
`

func (q *Queries) DeleteList(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteList, id)
	return err
}

const getListByID = `-- name: GetListByID :one
SELECT id, board_id, name, position, created_at, updated_at
FROM lists
WHERE id = $1
`

func (q *Queries) GetListByID(ctx context.Context, id uuid.UUID) (List, error) {
	row := q.db.QueryRow(ctx, getListByID, id)
	var i List
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMaxPositionForBoard = `-- name: GetMaxPositionForBoard :one
SELECT COALESCE(MAX(position), 0)::float8 FROM lists WHERE board_id = $1
`

func (q *Queries) GetMaxPositionForBoard(ctx context.Context, boardID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getMaxPositionForBoard, boardID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const listListsByBoard = `-- name: ListListsByBoard :many
SELECT id, board_id, name, position, created_at, updated_at
FROM lists
WHERE board_id = $1
ORDER BY position ASC
`

func (q *Queries) ListListsByBoard(ctx context.Context, boardID uuid.UUID) ([]List, error) {
	rows, err := q.db.Query(ctx, listListsByBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []List{}
	for rows.Next() {
		var i List
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateList = `-- name: UpdateList :one
UPDATE lists
SET name = $2, position = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, board_id, name, position, created_at, updated_at
`

type UpdateListParams struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Position float64   `json:"position"`
}

func (q *Queries) UpdateList(ctx context.Context, arg UpdateListParams) (List, error) {
	row := q.db.QueryRow(ctx, updateList, arg.ID, arg.Name, arg.Position)
	var i List
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
