// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addWorkspaceMember = `-- name: AddWorkspaceMember :one
INSERT INTO workspace_members (id, user_id, workspace_id, role, joined_at)
VALUES ($1, $2, $3, $4, NOW())
RETURNING id, user_id, workspace_id, role, joined_at
`

type AddWorkspaceMemberParams struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Role        Role      `json:"role"`
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, addWorkspaceMember,
		arg.ID,
		arg.UserID,
		arg.WorkspaceID,
		arg.Role,
	)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const countWorkspaceMembers = `-- name: CountWorkspaceMembers :one
SELECT COUNT(*) FROM workspace_members WHERE workspace_id = $1
`

func (q *Queries) CountWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkspaceMembers, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (id, name, description, slug, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id, name, description, slug, created_at, updated_at
`

type CreateWorkspaceParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Slug        string         `json:"slug"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Slug,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces WHERE id = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkspace, id)
	return err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, name, description, slug, created_at, updated_at
FROM workspaces
WHERE id = $1
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceBySlug = `-- name: GetWorkspaceBySlug :one
SELECT id, name, description, slug, created_at, updated_at
FROM workspaces
WHERE slug = $1
`

func (q *Queries) GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBySlug, slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceMember = `-- name: GetWorkspaceMember :one
SELECT id, user_id, workspace_id, role, joined_at
FROM workspace_members
WHERE user_id = $1 AND workspace_id = $2
`

type GetWorkspaceMemberParams struct {
	UserID      uuid.UUID `json:"user_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMember, arg.UserID, arg.WorkspaceID)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT wm.id, wm.user_id, wm.workspace_id, wm.role, wm.joined_at,
       u.name AS user_name, u.email AS user_email, u.avatar_url AS user_avatar_url
FROM workspace_members wm
JOIN users u ON u.id = wm.user_id
WHERE wm.workspace_id = $1
ORDER BY wm.joined_at ASC
`

type ListWorkspaceMembersRow struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	WorkspaceID   uuid.UUID      `json:"workspace_id"`
	Role          Role           `json:"role"`
	JoinedAt      time.Time      `json:"joined_at"`
	UserName      string         `json:"user_name"`
	UserEmail     string         `json:"user_email"`
	UserAvatarUrl sql.NullString `json:"user_avatar_url"`
}

func (q *Queries) ListWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceMembersRow{}
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkspaceID,
			&i.Role,
			&i.JoinedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesByUserID = `-- name: ListWorkspacesByUserID :many
SELECT w.id, w.name, w.description, w.slug, w.created_at, w.updated_at,
       wm.role
FROM workspaces w
JOIN workspace_members wm ON wm.workspace_id = w.id
WHERE wm.user_id = $1
ORDER BY w.created_at DESC
`

type ListWorkspacesByUserIDRow struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Slug        string         `json:"slug"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	Role        Role           `json:"role"`
}

func (q *Queries) ListWorkspacesByUserID(ctx context.Context, userID uuid.UUID) ([]ListWorkspacesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesByUserIDRow{}
	for rows.Next() {
		var i ListWorkspacesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWorkspaceMember = `-- name: RemoveWorkspaceMember :exec
DELETE FROM workspace_members
WHERE user_id = $1 AND workspace_id = $2
`

type RemoveWorkspaceMemberParams struct {
	UserID      uuid.UUID `json:"user_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) RemoveWorkspaceMember(ctx context.Context, arg RemoveWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, removeWorkspaceMember, arg.UserID, arg.WorkspaceID)
	return err
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces
SET name = $2, description = $3, slug = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, slug, created_at, updated_at
`

type UpdateWorkspaceParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Slug        string         `json:"slug"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Slug,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkspaceMemberRole = `-- name: UpdateWorkspaceMemberRole :one
UPDATE workspace_members
SET role = $3
WHERE user_id = $1 AND workspace_id = $2
RETURNING id, user_id, workspace_id, role, joined_at
`

type UpdateWorkspaceMemberRoleParams struct {
	UserID      uuid.UUID `json:"user_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Role        Role      `json:"role"`
}

func (q *Queries) UpdateWorkspaceMemberRole(ctx context.Context, arg UpdateWorkspaceMemberRoleParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceMemberRole, arg.UserID, arg.WorkspaceID, arg.Role)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}
